# Generated by Django 6.0.4 on 2026-04-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
